# syntax=docker/dockerfile:1

FROM node:18-buster-slim AS base

RUN apt-get update && apt-get install -y wget

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN mkdir -p /app

WORKDIR /app

COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .

FROM base AS dependencies

RUN npm install

FROM dependencies AS runtime

COPY . .