version: '3.9'

services:
  db:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secr3tPassw0rd123
    expose:
      - 1433
  
  aegis-backend:
    container_name: aegis-backend
    build:
      context: .
      dockerfile: Dockerfile.test
    image: aegis-backend
    command: npm start
    environment:
      NODE_ENV: test
      DB_HOST: db
      DB_USER: sa
      DB_PASSWORD: Secr3tPassw0rd123
      DB_NAME: master
    expose:
      - 2000
    depends_on:
      - db

  aegis-backend-tests:
    container_name: aegis-backend-tests
    image: aegis-backend
    command: dockerize
        -wait tcp://db:1433 -timeout 10s
        bash -c "npm test"
    environment:
      URL: http://aegis-backend:2000
      DB_HOST: db
      DB_USER: sa
      DB_PASSWORD: Secr3tPassw0rd123
      DB_NAME: master
    depends_on:
      - db
      - aegis-backend